{% set name = "nbdime" %}
{% set version = "0.1.2" %}
{% set sha256 = "4adb8ff052a7c778fb5f00872172a3790504de392eb7f23b6ae96b8a8165a695" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - nbdime=nbdime.__main__:main_dispatch
    - nbshow=nbdime.nbshowapp:main
    - nbdiff=nbdime.nbdiffapp:main
    - nbdiff-web=nbdime.webapp.nbdiffweb:main
    - nbmerge=nbdime.nbmergeapp:main
    - nbmerge-web=nbdime.webapp.nbmergeweb:main
    - git-nbdifftool=nbdime.gitdifftool:main
    - git-nbmergetool=nbdime.gitmergetool:main
    - git-nbdiffdriver=nbdime.gitdiffdriver:main
    - git-nbmergedriver=nbdime.gitmergedriver:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - nbformat
    - six
    - colorama
    - tornado
    - requests
    - backports.shutil_which

test:
  imports:
    - nbdime
  commands:
    - nbdime show -h
    - nbshow -h
    - nbdiff -h
    - nbdiff-web -h
    - nbmerge -h
    - nbmerge-web -h
    - git-nbdifftool -h
    - git-nbmergetool -h
    - git-nbdiffdriver -h
    - git-nbmergedriver -h

about:
  home: https://nbdime.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Diff and merge of Jupyter Notebooks'
  doc_url: https://nbdime.readthedocs.io/
  dev_url: https://github.com/jupyter/nbdime

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
    - ocefpaf
